import type { LayerConfig } from "../types";

const EDMONTON_API = "https://data.edmonton.ca/resource";

export const LAYER_CONFIGS: LayerConfig[] = [
  // ─── Infrastructure ───────────────────────────────────────────────
  {
    id: "neighbourhoods",
    name: "Neighbourhood Boundaries",
    description:
      "Official 2019 neighbourhood boundaries. Provides spatial context for all data layers across Edmonton.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/xu6q-xcmj.json?$limit=500`,
    type: "geojson",
    style: {
      color: "#6ee7b7",
      weight: 1.5,
      opacity: 0.5,
      fillColor: "#34d399",
      fillOpacity: 0.05,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "descriptiv", label: "Name" },
      { key: "neighbourh", label: "ID" },
    ],
    enabled: false,
  },
  {
    id: "permits",
    name: "Building Permits",
    description:
      "Recent building permits showing construction activity, development patterns, and building types across Edmonton.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/24uj-dj8v.json?$limit=800&$where=latitude IS NOT NULL&$order=issue_date DESC`,
    type: "point",
    style: {
      color: "#f97316",
      weight: 1,
      opacity: 0.9,
      fillColor: "#fb923c",
      fillOpacity: 0.7,
    },
    pointColor: "#f97316",
    pointRadius: 5,
    maxFeatures: 800,
    popupFields: [
      { key: "job_description", label: "Description" },
      { key: "job_category", label: "Category" },
      { key: "work_type", label: "Work Type" },
      { key: "building_type", label: "Building Type" },
      { key: "construction_value", label: "Value", format: "currency" },
      { key: "address", label: "Address" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "issue_date", label: "Issue Date" },
    ],
    enabled: false,
  },
  {
    id: "properties",
    name: "Property Assessments",
    description:
      "Top assessed property values across Edmonton. Shows land value distribution, urban density, and tax classes.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/q7d6-ambg.json?$limit=1000&$where=latitude IS NOT NULL&$order=assessed_value DESC`,
    type: "point",
    style: {
      color: "#a855f7",
      weight: 1,
      opacity: 0.9,
      fillColor: "#c084fc",
      fillOpacity: 0.6,
    },
    pointColor: "#a855f7",
    pointRadius: 4,
    maxFeatures: 1000,
    popupFields: [
      { key: "street_name", label: "Address" },
      { key: "assessed_value", label: "Assessed Value", format: "currency" },
      { key: "tax_class", label: "Tax Class" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
      { key: "garage", label: "Garage" },
    ],
    enabled: false,
  },
  {
    id: "subdivisions",
    name: "Subdivision Applications",
    description:
      "Residential subdivision applications in mature neighbourhoods showing urban densification and infill development.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/5mh4-z7dk.json?$limit=500`,
    type: "geojson",
    geomField: "geometry_multipolygon",
    style: {
      color: "#facc15",
      weight: 2,
      opacity: 0.8,
      fillColor: "#eab308",
      fillOpacity: 0.25,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "address", label: "Address" },
      { key: "status", label: "Status" },
      { key: "zoning", label: "Zoning" },
      { key: "neighbourhood_name", label: "Neighbourhood" },
      { key: "ward_name", label: "Ward" },
      { key: "filenumber", label: "File #" },
    ],
    enabled: false,
  },
  {
    id: "lrt",
    name: "LRT Stations",
    description:
      "All 36 LRT stations along Edmonton's light rail transit lines including park-and-ride and pedway connections.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/fhxi-cnhe.json?$limit=100`,
    type: "point",
    style: {
      color: "#22d3ee",
      weight: 1,
      opacity: 0.9,
      fillColor: "#06b6d4",
      fillOpacity: 0.8,
    },
    pointColor: "#22d3ee",
    pointRadius: 7,
    maxFeatures: 100,
    popupFields: [
      { key: "lrt_stop_description", label: "Station" },
      { key: "lrt_stop_number", label: "Stop #" },
    ],
    enabled: false,
  },
  {
    id: "traffic",
    name: "Traffic Disruptions",
    description:
      "Active road closures, construction, and travel delays across Edmonton updated multiple times daily.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/k4tx-5k8p.json?$limit=500&$order=start_date DESC`,
    type: "point",
    latField: "point",
    style: {
      color: "#ef4444",
      weight: 1,
      opacity: 0.9,
      fillColor: "#f87171",
      fillOpacity: 0.7,
    },
    pointColor: "#ef4444",
    pointRadius: 5,
    maxFeatures: 500,
    popupFields: [
      { key: "description", label: "Description" },
      { key: "activity_type", label: "Type" },
      { key: "on_street", label: "Street" },
      { key: "impact", label: "Impact" },
      { key: "status", label: "Status" },
      { key: "closure", label: "Closure" },
      { key: "start_date", label: "Start" },
      { key: "finish_date", label: "End" },
    ],
    enabled: false,
  },
  {
    id: "recreation",
    name: "Recreation Facilities",
    description:
      "City-owned recreation facilities including pools, arenas, sports fields, golf courses, and community centres.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/nz3t-vyg3.json?$limit=500`,
    type: "point",
    style: {
      color: "#10b981",
      weight: 1,
      opacity: 0.9,
      fillColor: "#34d399",
      fillOpacity: 0.7,
    },
    pointColor: "#10b981",
    pointRadius: 6,
    maxFeatures: 500,
    popupFields: [
      { key: "facility_name", label: "Name" },
      { key: "facility_type", label: "Type" },
      { key: "category", label: "Category" },
      { key: "address", label: "Address" },
    ],
    enabled: false,
  },

  // ─── Environment ──────────────────────────────────────────────────
  {
    id: "drainage",
    name: "Stormwater Facilities",
    description:
      "Storm water management ponds and facilities (wet/dry) across Edmonton. Data from EPCOR and City drainage services.",
    category: "environment",
    endpoint: `${EDMONTON_API}/kiu8-nsmp.json?$limit=500`,
    type: "polygon",
    style: {
      color: "#38bdf8",
      weight: 2,
      opacity: 0.8,
      fillColor: "#0ea5e9",
      fillOpacity: 0.3,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "description", label: "Name" },
      { key: "storm_type", label: "Type" },
      { key: "facility_owner", label: "Owner" },
      { key: "year", label: "Year Built", format: "year" },
      { key: "neighbourhood_name", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
    ],
    enabled: true,
  },
  {
    id: "airquality",
    name: "Air Quality Stations",
    description:
      "Edmonton-area air quality monitoring stations with historical readings from the Alberta Capital Airshed.",
    category: "environment",
    endpoint: `${EDMONTON_API}/44dx-d5qn.json?$select=monitoring_station_name,latitude,longitude,parameter_measured,average_daily_value,unit_of_measure,date_measured&$where=latitude IS NOT NULL&$order=date_measured DESC&$limit=200`,
    type: "point",
    style: {
      color: "#a3e635",
      weight: 1,
      opacity: 0.9,
      fillColor: "#84cc16",
      fillOpacity: 0.7,
    },
    pointColor: "#a3e635",
    pointRadius: 8,
    maxFeatures: 200,
    popupFields: [
      { key: "monitoring_station_name", label: "Station" },
      { key: "parameter_measured", label: "Parameter" },
      { key: "average_daily_value", label: "Value", format: "number" },
      { key: "unit_of_measure", label: "Unit" },
      { key: "date_measured", label: "Date" },
    ],
    enabled: false,
  },
  {
    id: "waterstations",
    name: "Water Filling Stations",
    description:
      "Seasonal and year-round public water bottle filling stations available across Edmonton.",
    category: "environment",
    endpoint: `${EDMONTON_API}/dj78-t8ab.json?$limit=200`,
    type: "point",
    latField: "geometry",
    style: {
      color: "#60a5fa",
      weight: 1,
      opacity: 0.9,
      fillColor: "#3b82f6",
      fillOpacity: 0.7,
    },
    pointColor: "#60a5fa",
    pointRadius: 6,
    maxFeatures: 200,
    popupFields: [
      { key: "location_name", label: "Name" },
      { key: "filling_station_type", label: "Type" },
      { key: "hours_of_operation", label: "Hours" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
      { key: "nearest_intersection", label: "Intersection" },
    ],
    enabled: false,
  },
];

export const EDMONTON_CENTER: [number, number] = [53.5461, -113.4938];
export const DEFAULT_ZOOM = 11;

export const CATEGORY_META = {
  infrastructure: { label: "Infrastructure", icon: "building" },
  environment: { label: "Environment", icon: "leaf" },
  energy: { label: "Energy & Mining", icon: "bolt" },
} as const;
