import type { LayerConfig } from "../types";

const EDMONTON_API = "https://data.edmonton.ca/resource";
const WEATHER_API =
  import.meta.env.DEV
    ? "/weatherapi"
    : "https://api.weather.gc.ca";

// Dynamic 7-day window for daily precipitation queries
const today = new Date();
const weekAgo = new Date(today);
weekAgo.setDate(today.getDate() - 7);
const fmtDate = (d: Date) => d.toISOString().slice(0, 10);
const DAILY_DATE_RANGE = `${fmtDate(weekAgo)}/${fmtDate(today)}`;

const ARCGIS_ORIGIN =
  import.meta.env.DEV
    ? "/arcgis"
    : "https://services.arcgis.com";
const AB_FLOOD_BASE =
  `${ARCGIS_ORIGIN}/wjcPoefzjpzCgffS/arcgis/rest/services/AlbertaFloodMapping_gdb/FeatureServer`;
const abFloodLayer = (layerId: number) => `${AB_FLOOD_BASE}/${layerId}`;

export const LAYER_CONFIGS: LayerConfig[] = [
  // ─── Infrastructure ───────────────────────────────────────────────
  {
    id: "neighbourhoods",
    name: "Neighbourhood Boundaries",
    description:
      "Official 2019 neighbourhood boundaries. Provides spatial context for all data layers across Edmonton.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/xu6q-xcmj.json?$limit=500`,
    type: "geojson",
    style: {
      color: "#6ee7b7",
      weight: 1.5,
      opacity: 0.5,
      fillColor: "#34d399",
      fillOpacity: 0.05,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "descriptiv", label: "Name" },
      { key: "neighbourh", label: "ID" },
    ],
    enabled: false,
  },
  {
    id: "permits",
    name: "Building Permits",
    description:
      "Recent building permits showing construction activity, development patterns, and building types across Edmonton.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/24uj-dj8v.json?$limit=800&$where=latitude IS NOT NULL&$order=issue_date DESC`,
    type: "point",
    style: {
      color: "#f97316",
      weight: 1,
      opacity: 0.9,
      fillColor: "#fb923c",
      fillOpacity: 0.7,
    },
    pointColor: "#f97316",
    pointRadius: 5,
    maxFeatures: 800,
    popupFields: [
      { key: "job_description", label: "Description" },
      { key: "job_category", label: "Category" },
      { key: "work_type", label: "Work Type" },
      { key: "building_type", label: "Building Type" },
      { key: "construction_value", label: "Value", format: "currency" },
      { key: "address", label: "Address" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "issue_date", label: "Issue Date" },
    ],
    enabled: false,
  },
  {
    id: "properties",
    name: "Property Assessments",
    description:
      "Top assessed property values across Edmonton. Shows land value distribution, urban density, and tax classes.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/q7d6-ambg.json?$limit=1000&$where=latitude IS NOT NULL&$order=assessed_value DESC`,
    type: "point",
    style: {
      color: "#a855f7",
      weight: 1,
      opacity: 0.9,
      fillColor: "#c084fc",
      fillOpacity: 0.6,
    },
    pointColor: "#a855f7",
    pointRadius: 4,
    maxFeatures: 1000,
    popupFields: [
      { key: "street_name", label: "Address" },
      { key: "assessed_value", label: "Assessed Value", format: "currency" },
      { key: "tax_class", label: "Tax Class" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
      { key: "garage", label: "Garage" },
    ],
    enabled: false,
  },
  {
    id: "property-details",
    name: "Property Details (Lot Size & Zoning)",
    description:
      "Edmonton property details including lot area (m²), building area, zoning classification, year built, and legal description. Essential for engineering site analysis.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/dkk9-cj3x.json?$limit=1000&$where=latitude IS NOT NULL AND lot_size > 0`,
    type: "point",
    style: {
      color: "#d946ef",
      weight: 1,
      opacity: 0.9,
      fillColor: "#e879f9",
      fillOpacity: 0.6,
    },
    pointColor: "#d946ef",
    pointRadius: 4,
    maxFeatures: 1000,
    popupFields: [
      { key: "house_number", label: "House #" },
      { key: "street_name", label: "Street" },
      { key: "lot_size", label: "Lot Area (m²)", format: "number" },
      { key: "total_gross_area", label: "Building Area (m²)", format: "number" },
      { key: "zoning", label: "Zoning" },
      { key: "year_built", label: "Year Built", format: "year" },
      { key: "legal_description", label: "Legal Description" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
    ],
    enabled: false,
  },
  {
    id: "subdivisions",
    name: "Subdivision Applications",
    description:
      "Residential subdivision applications in mature neighbourhoods showing urban densification and infill development.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/5mh4-z7dk.json?$limit=500`,
    type: "geojson",
    geomField: "geometry_multipolygon",
    style: {
      color: "#facc15",
      weight: 2,
      opacity: 0.8,
      fillColor: "#eab308",
      fillOpacity: 0.25,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "address", label: "Address" },
      { key: "status", label: "Status" },
      { key: "zoning", label: "Zoning" },
      { key: "neighbourhood_name", label: "Neighbourhood" },
      { key: "ward_name", label: "Ward" },
      { key: "filenumber", label: "File #" },
    ],
    enabled: false,
  },
  {
    id: "lrt",
    name: "LRT Stations",
    description:
      "All 36 LRT stations along Edmonton's light rail transit lines including park-and-ride and pedway connections.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/fhxi-cnhe.json?$limit=100`,
    type: "point",
    style: {
      color: "#22d3ee",
      weight: 1,
      opacity: 0.9,
      fillColor: "#06b6d4",
      fillOpacity: 0.8,
    },
    pointColor: "#22d3ee",
    pointRadius: 7,
    maxFeatures: 100,
    popupFields: [
      { key: "lrt_stop_description", label: "Station" },
      { key: "lrt_stop_number", label: "Stop #" },
    ],
    enabled: false,
  },
  {
    id: "traffic",
    name: "Traffic Disruptions",
    description:
      "Active road closures, construction, and travel delays across Edmonton updated multiple times daily.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/k4tx-5k8p.json?$limit=500&$order=start_date DESC`,
    type: "point",
    latField: "point",
    style: {
      color: "#ef4444",
      weight: 1,
      opacity: 0.9,
      fillColor: "#f87171",
      fillOpacity: 0.7,
    },
    pointColor: "#ef4444",
    pointRadius: 5,
    maxFeatures: 500,
    popupFields: [
      { key: "description", label: "Description" },
      { key: "activity_type", label: "Type" },
      { key: "on_street", label: "Street" },
      { key: "impact", label: "Impact" },
      { key: "status", label: "Status" },
      { key: "closure", label: "Closure" },
      { key: "start_date", label: "Start" },
      { key: "finish_date", label: "End" },
    ],
    enabled: false,
  },
  {
    id: "recreation",
    name: "Recreation Facilities",
    description:
      "City-owned recreation facilities including pools, arenas, sports fields, golf courses, and community centres.",
    category: "infrastructure",
    endpoint: `${EDMONTON_API}/nz3t-vyg3.json?$limit=500`,
    type: "point",
    style: {
      color: "#10b981",
      weight: 1,
      opacity: 0.9,
      fillColor: "#34d399",
      fillOpacity: 0.7,
    },
    pointColor: "#10b981",
    pointRadius: 6,
    maxFeatures: 500,
    popupFields: [
      { key: "facility_name", label: "Name" },
      { key: "facility_type", label: "Type" },
      { key: "category", label: "Category" },
      { key: "address", label: "Address" },
    ],
    enabled: false,
  },

  // ─── Environment ──────────────────────────────────────────────────
  {
    id: "drainage",
    name: "Stormwater Facilities",
    description:
      "Storm water management ponds and facilities (wet/dry) across Edmonton. Data from EPCOR and City drainage services.",
    category: "environment",
    endpoint: `${EDMONTON_API}/kiu8-nsmp.json?$limit=500`,
    type: "polygon",
    style: {
      color: "#38bdf8",
      weight: 2,
      opacity: 0.8,
      fillColor: "#0ea5e9",
      fillOpacity: 0.3,
    },
    maxFeatures: 500,
    popupFields: [
      { key: "description", label: "Name" },
      { key: "storm_type", label: "Type" },
      { key: "facility_owner", label: "Owner" },
      { key: "year", label: "Year Built", format: "year" },
      { key: "neighbourhood_name", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
    ],
    enabled: true,
  },
  {
    id: "airquality",
    name: "Air Quality Stations",
    description:
      "Edmonton-area air quality monitoring stations with historical readings from the Alberta Capital Airshed.",
    category: "environment",
    endpoint: `${EDMONTON_API}/44dx-d5qn.json?$select=monitoring_station_name,latitude,longitude,parameter_measured,average_daily_value,unit_of_measure,date_measured&$where=latitude IS NOT NULL&$order=date_measured DESC&$limit=200`,
    type: "point",
    style: {
      color: "#a3e635",
      weight: 1,
      opacity: 0.9,
      fillColor: "#84cc16",
      fillOpacity: 0.7,
    },
    pointColor: "#a3e635",
    pointRadius: 8,
    maxFeatures: 200,
    popupFields: [
      { key: "monitoring_station_name", label: "Station" },
      { key: "parameter_measured", label: "Parameter" },
      { key: "average_daily_value", label: "Value", format: "number" },
      { key: "unit_of_measure", label: "Unit" },
      { key: "date_measured", label: "Date" },
    ],
    enabled: false,
  },
  {
    id: "waterstations",
    name: "Water Filling Stations",
    description:
      "Seasonal and year-round public water bottle filling stations available across Edmonton.",
    category: "environment",
    endpoint: `${EDMONTON_API}/dj78-t8ab.json?$limit=200`,
    type: "point",
    latField: "geometry",
    style: {
      color: "#60a5fa",
      weight: 1,
      opacity: 0.9,
      fillColor: "#3b82f6",
      fillOpacity: 0.7,
    },
    pointColor: "#60a5fa",
    pointRadius: 6,
    maxFeatures: 200,
    popupFields: [
      { key: "location_name", label: "Name" },
      { key: "filling_station_type", label: "Type" },
      { key: "hours_of_operation", label: "Hours" },
      { key: "neighbourhood", label: "Neighbourhood" },
      { key: "ward", label: "Ward" },
      { key: "nearest_intersection", label: "Intersection" },
    ],
    enabled: false,
  },

  // ─── Precipitation & Climate (Province-wide, Environment Canada) ─
  {
    id: "climate-stations",
    name: "Climate Stations (Alberta)",
    description:
      "Active Environment Canada weather stations across Alberta. Shows station location, type, and data availability.",
    category: "precipitation",
    endpoint: `${WEATHER_API}/collections/climate-stations/items?f=json&limit=500&PROVINCE_CODE=AB`,
    source: "geojson",
    type: "point",
    style: {
      color: "#fbbf24",
      weight: 1,
      opacity: 0.9,
      fillColor: "#f59e0b",
      fillOpacity: 0.7,
    },
    pointColor: "#fbbf24",
    pointRadius: 6,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "CLIMATE_IDENTIFIER", label: "Climate ID" },
      { key: "STATION_TYPE", label: "Type" },
      { key: "ELEVATION", label: "Elevation (m)" },
      { key: "FIRST_DATE", label: "Data Since" },
      { key: "LAST_DATE", label: "Latest Data" },
      { key: "HAS_NORMALS_DATA", label: "Has Normals" },
    ],
    enabled: false,
  },
  {
    id: "precip-daily",
    name: "Daily Precipitation (Alberta)",
    description:
      "Recent daily precipitation, temperature, and snowfall observations from Alberta weather stations (last 7 days).",
    category: "precipitation",
    endpoint: `${WEATHER_API}/collections/climate-daily/items?f=json&limit=500&PROVINCE_CODE=AB&sortby=-LOCAL_DATE&datetime=${DAILY_DATE_RANGE}`,
    source: "geojson",
    type: "point",
    style: {
      color: "#38bdf8",
      weight: 1,
      opacity: 0.9,
      fillColor: "#0ea5e9",
      fillOpacity: 0.8,
    },
    pointColor: "#38bdf8",
    pointRadius: 7,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "LOCAL_DATE", label: "Date" },
      { key: "TOTAL_PRECIPITATION", label: "Precipitation (mm)", format: "number" },
      { key: "TOTAL_RAIN", label: "Rain (mm)", format: "number" },
      { key: "TOTAL_SNOW", label: "Snow (cm)", format: "number" },
      { key: "SNOW_ON_GROUND", label: "Snow Depth (cm)", format: "number" },
      { key: "MEAN_TEMPERATURE", label: "Mean Temp (°C)", format: "number" },
      { key: "MIN_TEMPERATURE", label: "Min Temp (°C)", format: "number" },
      { key: "MAX_TEMPERATURE", label: "Max Temp (°C)", format: "number" },
    ],
    enabled: false,
  },
  {
    id: "precip-normals",
    name: "Precipitation Normals (30-yr Avg)",
    description:
      "Annual total precipitation depth (mm) averaged over 1981-2010 at each station. Baseline for engineering calculations.",
    category: "precipitation",
    endpoint: `${WEATHER_API}/collections/climate-normals/items?f=json&limit=500&PROVINCE_CODE=AB&NORMAL_ID=56&MONTH=13`,
    source: "geojson",
    type: "point",
    style: {
      color: "#818cf8",
      weight: 1,
      opacity: 0.9,
      fillColor: "#6366f1",
      fillOpacity: 0.8,
    },
    pointColor: "#818cf8",
    pointRadius: 8,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "CLIMATE_IDENTIFIER", label: "Climate ID" },
      { key: "VALUE", label: "Annual Precip (mm)", format: "number" },
      { key: "PERIOD_BEGIN", label: "Period Start", format: "year" },
      { key: "PERIOD_END", label: "Period End", format: "year" },
      { key: "YEAR_COUNT_NORMAL_PERIOD", label: "Years of Data", format: "number" },
      { key: "PERCENT_OF_POSSIBLE_OBS", label: "Data Coverage (%)", format: "number" },
    ],
    enabled: false,
  },
  {
    id: "precip-monthly",
    name: "Monthly Precipitation Summary",
    description:
      "Monthly precipitation totals, snowfall, and temperature summaries from Alberta stations. Latest available month.",
    category: "precipitation",
    endpoint: `${WEATHER_API}/collections/climate-monthly/items?f=json&limit=500&PROVINCE_CODE=AB&sortby=-LOCAL_DATE`,
    source: "geojson",
    type: "point",
    style: {
      color: "#c084fc",
      weight: 1,
      opacity: 0.9,
      fillColor: "#a855f7",
      fillOpacity: 0.7,
    },
    pointColor: "#c084fc",
    pointRadius: 7,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "LOCAL_DATE", label: "Month" },
      { key: "TOTAL_PRECIPITATION", label: "Total Precip (mm)", format: "number" },
      { key: "NORMAL_PRECIPITATION", label: "Normal Precip (mm)", format: "number" },
      { key: "TOTAL_SNOWFALL", label: "Snowfall (cm)", format: "number" },
      { key: "SNOW_ON_GROUND_LAST_DAY", label: "Snow Depth Last Day (cm)", format: "number" },
      { key: "DAYS_WITH_PRECIP_GE_1MM", label: "Days >= 1mm Precip", format: "number" },
      { key: "MEAN_TEMPERATURE", label: "Mean Temp (°C)", format: "number" },
      { key: "HEATING_DEGREE_DAYS", label: "Heating Degree Days", format: "number" },
    ],
    enabled: false,
  },
  {
    id: "snowfall-normals",
    name: "Snowfall Normals (30-yr Avg)",
    description:
      "Annual total snowfall depth (cm) averaged over 1981-2010. Critical for snowmelt runoff and spring flood modeling.",
    category: "precipitation",
    endpoint: `${WEATHER_API}/collections/climate-normals/items?f=json&limit=500&PROVINCE_CODE=AB&NORMAL_ID=54&MONTH=13`,
    source: "geojson",
    type: "point",
    style: {
      color: "#e2e8f0",
      weight: 1,
      opacity: 0.9,
      fillColor: "#cbd5e1",
      fillOpacity: 0.7,
    },
    pointColor: "#e2e8f0",
    pointRadius: 7,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "CLIMATE_IDENTIFIER", label: "Climate ID" },
      { key: "VALUE", label: "Annual Snowfall (cm)", format: "number" },
      { key: "PERIOD_BEGIN", label: "Period Start", format: "year" },
      { key: "PERIOD_END", label: "Period End", format: "year" },
      { key: "YEAR_COUNT_NORMAL_PERIOD", label: "Years of Data", format: "number" },
    ],
    enabled: false,
  },
  {
    id: "hydro-stations",
    name: "Hydrometric Stations (Alberta)",
    description:
      "River and lake water level/flow monitoring stations across Alberta. Real-time and historical hydrometric data.",
    category: "flood",
    endpoint: `${WEATHER_API}/collections/hydrometric-stations/items?f=json&limit=500&PROV_TERR_STATE_LOC=AB`,
    source: "geojson",
    type: "point",
    style: {
      color: "#2dd4bf",
      weight: 1,
      opacity: 0.9,
      fillColor: "#14b8a6",
      fillOpacity: 0.7,
    },
    pointColor: "#2dd4bf",
    pointRadius: 5,
    maxFeatures: 500,
    popupFields: [
      { key: "STATION_NAME", label: "Station" },
      { key: "STATION_NUMBER", label: "Station #" },
      { key: "DRAINAGE_AREA_GROSS", label: "Drainage Area (km²)", format: "number" },
      { key: "STATION_STATUS", label: "Status" },
      { key: "STATION_OPERATION_SCHEDULE", label: "Operation" },
      { key: "DATA_TYPE", label: "Data Type" },
      { key: "STATION_CONTRIBUTOR", label: "Contributor" },
    ],
    enabled: false,
  },

  // ─── Alberta Flood Hazard (Province-wide) ───────────────────────
  {
    id: "flood-hazard",
    name: "Flood Hazard Areas",
    description:
      "Provincial flood hazard zones showing floodway and flood fringe areas for the 1:100 design flood across Alberta.",
    category: "flood",
    endpoint: abFloodLayer(0),
    source: "arcgis",
    type: "polygon",
    style: {
      color: "#f43f5e",
      weight: 1.5,
      opacity: 0.8,
      fillColor: "#e11d48",
      fillOpacity: 0.3,
    },
    maxFeatures: 2000,
    popupFields: [
      { key: "RiverName", label: "River" },
      { key: "StudyName", label: "Study" },
      { key: "FloodMechanism", label: "Mechanism" },
      { key: "Flow_Regime", label: "Flow Regime" },
      { key: "Two_Zone", label: "Two Zone" },
      { key: "Multi_Zone", label: "Multi Zone" },
    ],
    enabled: false,
  },
  {
    id: "flood-100yr",
    name: "100-Year Flood Inundation",
    description:
      "Areas at risk during a 1:100 year open water flood (1% chance per year). The design standard for Alberta communities.",
    category: "flood",
    endpoint: abFloodLayer(11),
    source: "arcgis",
    type: "polygon",
    style: {
      color: "#3b82f6",
      weight: 1.5,
      opacity: 0.8,
      fillColor: "#2563eb",
      fillOpacity: 0.3,
    },
    maxFeatures: 2000,
    popupFields: [
      { key: "RiverName", label: "River" },
      { key: "StudyName", label: "Study" },
      { key: "FloodReturnPeriod", label: "Return Period (yrs)", format: "number" },
      { key: "FloodProbability", label: "Annual Probability" },
      { key: "InundationZone", label: "Zone" },
      { key: "FloodMechanism", label: "Mechanism" },
    ],
    enabled: false,
  },
  {
    id: "flood-200yr",
    name: "200-Year Flood Inundation",
    description:
      "Areas at risk during a 1:200 year open water flood (0.5% chance per year). Wider extent than the 100-year scenario.",
    category: "flood",
    endpoint: abFloodLayer(12),
    source: "arcgis",
    type: "polygon",
    style: {
      color: "#8b5cf6",
      weight: 1.5,
      opacity: 0.8,
      fillColor: "#7c3aed",
      fillOpacity: 0.25,
    },
    maxFeatures: 2000,
    popupFields: [
      { key: "RiverName", label: "River" },
      { key: "StudyName", label: "Study" },
      { key: "FloodReturnPeriod", label: "Return Period (yrs)", format: "number" },
      { key: "FloodProbability", label: "Annual Probability" },
      { key: "InundationZone", label: "Zone" },
      { key: "FloodMechanism", label: "Mechanism" },
    ],
    enabled: false,
  },
  {
    id: "flood-icejam-100yr",
    name: "Ice Jam Flood (100-Year)",
    description:
      "Flood zones from 1:100 year ice jam events. Ice jams cause unique flooding patterns along Alberta rivers in spring.",
    category: "flood",
    endpoint: abFloodLayer(2),
    source: "arcgis",
    type: "polygon",
    style: {
      color: "#06b6d4",
      weight: 1.5,
      opacity: 0.8,
      fillColor: "#0891b2",
      fillOpacity: 0.3,
    },
    maxFeatures: 2000,
    popupFields: [
      { key: "RiverName", label: "River" },
      { key: "StudyName", label: "Study" },
      { key: "FloodReturnPeriod", label: "Return Period (yrs)", format: "number" },
      { key: "FloodProbability", label: "Annual Probability" },
      { key: "InundationZone", label: "Zone" },
      { key: "FloodMechanism", label: "Mechanism" },
    ],
    enabled: false,
  },
  {
    id: "flood-500yr",
    name: "500-Year Flood Inundation",
    description:
      "Extreme scenario — areas at risk during a 1:500 year flood (0.2% chance per year). Shows worst-case planning extent.",
    category: "flood",
    endpoint: abFloodLayer(14),
    source: "arcgis",
    type: "polygon",
    style: {
      color: "#ec4899",
      weight: 1.5,
      opacity: 0.8,
      fillColor: "#db2777",
      fillOpacity: 0.2,
    },
    maxFeatures: 2000,
    popupFields: [
      { key: "RiverName", label: "River" },
      { key: "StudyName", label: "Study" },
      { key: "FloodReturnPeriod", label: "Return Period (yrs)", format: "number" },
      { key: "FloodProbability", label: "Annual Probability" },
      { key: "InundationZone", label: "Zone" },
      { key: "FloodMechanism", label: "Mechanism" },
    ],
    enabled: false,
  },
];

export const ALBERTA_CENTER: [number, number] = [53.9333, -116.5765];
export const EDMONTON_CENTER: [number, number] = [53.5461, -113.4938];
export const DEFAULT_ZOOM = 6;

export const CATEGORY_META = {
  infrastructure: { label: "Infrastructure", icon: "building" },
  environment: { label: "Environment", icon: "leaf" },
  precipitation: { label: "Precipitation & Climate", icon: "precip" },
  flood: { label: "Flood Hazard", icon: "flood" },
  energy: { label: "Energy & Mining", icon: "bolt" },
} as const;
